let date = new Date()
console.log(date)
let christmas = new Date()
christmas.setFullYear(2022, 11, 25)
console.log(christmas)
let difference = christmas.getTime() - date.getTime()
console.log(difference)
let days = Math.ceil(difference / (1000 * 3600 * 24))
console.log(days)